version: '3'
services:
  psql_db:
    image: postgres:latest
    container_name: psql_server_kafka
    ports:
      - 5435:5432
    restart: on-failure
    environment:
      POSTGRES_MULTIPLE_DATABASES: producer_db,consumer_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: on-failure

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "metric:4:1"
    volumes:
      - kafka:/data
    restart: on-failure

volumes:
  database-data:
  kafka: